//#region Type to data
type TType = TTypeText | TTypeNumeric | TTypeDate | TTypeSpatial;
type TTypeNumeric = 'INT' | 'TINYINT' | 'SMALLINT' | 'MEDIUMINT' | 'BIGINT' | 'DECIMAL' | 'FLOAT' | 'DOUBLE' | 'DOUBLE';
type TTypeText = 'VARCHAR' | 'TEXT' | 'CHAR' | 'TINTEXT' | 'BINARY' | 'VARBINARY' | 'TINYBLOB' | 'BLOB' | 'MEDIUMBLOB' | 'LONGBLOB' | 'MEDIUMTEXT' | 'LONGTEXT' | 'ENUM' | 'SET';
type TTypeDate = 'DATE' | 'TIME' | 'DATETIME' | 'TIMESTAMP' | 'YEAR';
type TTypeSpatial = 'GEOMETRY' | 'POINT' | 'LINESTRING' | 'MULTIPOLYGON' | 'MULTIPOINT' | 'MULTILINESTRING' | 'GEOMETRYCOLLECTION' | 'POLYGON';
//#endregion
type TCompuestSentence = 'CREATE TABLE' | 'DROP TABLE' | 'ALTER TABLE' | 'IF EXISTS' | 'IF NOT EXISTS' | 'ADD CONSTRAINT';

type TSentence = 'DELETE' | 'CREATE' | 'UPDATE' | 'SELECT' | 'SHOW' | 'DROP' | 'ALTER' | 'MODIFY';
type TDatabase = 'COLUMN' | 'TABLE' | TDatabaseAttribute;
type TDatabaseAttribute = 'PRIMARY KEY' | 'NOT NULL' | 'UNIQUE' | 'AUTO_INCREMENT' | 'COMMENT' | 'DEFAULT' | 'CHARACTER SET' | 'COLLATE' | 'DEFAULT CHARSET' | 'ENGINE';
// Rerence options in foreignKey
type TReferenceOptions = 'RESTRICT' | 'CASCADE' | 'SET NULL' | 'NO ACTION' | 'SET DEFAULT';

type TCharset = 'BIG5' | 'DEC8' | 'CP850' | 'HP8' | 'KOI8R' | 'LATIN1' | 'LATIN2' | 'SWE7' | 'ASCII' | 'UJIS' | 'SJIS' | 'HEBREW' | 'TIS620' | 'EUCKR' | 'KOI8U' | 'GB2312' | 'GREEK' | 'CP1250' | 'GBK' | 'LATIN5' | 'ARMSCII8' | 'UTF8' | 'UCS2' | 'CP866' | 'KEYBCS2' | 'MACCE' | 'MACROMAN' | 'CP852' | 'LATIN7' | 'UTF8MB4' | 'CP1251' | 'UTF16' | 'UTF16LE' | 'CP1256' | 'CP1257' | 'UTF32' | 'BINARY' | 'GEOSTD8' | 'CP932' | 'EUCJPMS';
type TEngine = 'InnoDB' | 'Aria' | 'CSV' | 'MEMORY' | 'MyISAM' | 'NDB' | 'BLACKHOLE' | 'ARCHIVE' | 'SEQUENCE' | 'MRG_MyISAM' | 'PERFORMANCE_SCHEMA';

//#region Collation
type TCollation = TCollationUtf8 | TCollationBig5 | TCollationDec8 | TCollationCp850 | TCollationHp8 | TCollationKoi8r | TCollationLatin1 |
    TCollationLatin2 | TCollationSwe7 | TCollationAscii | TCollationUjis | TCollationSjis | TCollationHebrew | TCollationTis620 | TCollationEuckr | TCollationKoi8u | TCollationGb2312 | TCollationGreek | TCollationCp1250 | TCollationGbk | TCollationLatin5 | TCollationArmscii8 | TCollationUcs2 | TCollationCp866 | TCollationKeybcs2 | TCollationMacce | TCollationMacroman | TCollationCp852 | TCollationLatin7 | TCollationUtf8mb4 | TCollationCp1251 | TCollationUtf16 | TCollationCp1256 | TCollationCp1257 | TCollationUtf32 | TCollationBinary | TCollationGeostd8 | TCollationCp932 | TCollationEucjpms;
type ICollation<T extends TCharset> = TCollationUtf8;

type TCollationUtf8 = 'UTF8_GENERAL_CI' | 'UTF8_BIN' | 'UTF8_UNICODE_CI' | 'UTF8_ICELANDIC_CI' | 'UTF8_LATVIAN_CI' | 'UTF8_ROMANIAN_CI' | 'UTF8_SLOVENIAN_CI' | 'UTF8_POLISH_CI' | 'UTF8_ESTONIAN_CI' | 'UTF8_SPANISH_CI' | 'UTF8_SWEDISH_CI' | 'UTF8_TURKISH_CI' | 'UTF8_CZECH_CI' | 'UTF8_DANISH_CI' | 'UTF8_LITHUANIAN_CI' | 'UTF8_SLOVAK_CI' | 'UTF8_SPANISH2_CI' | 'UTF8_ROMAN_CI' | 'UTF8_PERSIAN_CI' | 'UTF8_ESPERANTO_CI' | 'UTF8_HUNGARIAN_CI' | 'UTF8_SINHALA_CI' | 'UTF8_GERMAN2_CI' | 'UTF8_CROATIAN_MYSQL561_CI' | 'UTF8_UNICODE_520_CI' | 'UTF8_VIETNAMESE_CI' | 'UTF8_GENERAL_MYSQL500_CI' | 'UTF8_CROATIAN_CI' | 'UTF8_MYANMAR_CI' | 'UTF8_THAI_520_W2' | 'UTF8_GENERAL_NOPAD_CI' | 'UTF8_NOPAD_BIN' | 'UTF8_UNICODE_NOPAD_CI' | 'UTF8_UNICODE_520_NOPAD_CI';
type TCollationBig5 = 'BIG5_CHINESE_CI' | 'BIG5_BIN' | 'BIG5_CHINESE_NOPAD_CI' | 'BIG5_NOPAD_BIN';
type TCollationDec8 = 'DEC8_SWEDISH_CI' | 'DEC8_BIN' | 'DEC8_SWEDISH_NOPAD_CI' | 'DEC8_NOPAD_BIN';
type TCollationCp850 = 'CP850_GENERAL_CI' | 'CP850_BIN' | 'CP850_GENERAL_NOPAD_CI' | 'CP850_NOPAD_BIN';
type TCollationHp8 = 'HP8_ENGLISH_CI' | 'HP8_BIN' | 'HP8_ENGLISH_NOPAD_CI' | 'HP8_NOPAD_BIN';
type TCollationKoi8r = 'KOI8R_GENERAL_CI' | 'KOI8R_BIN' | 'KOI8R_GENERAL_NOPAD_CI' | 'KOI8R_NOPAD_BIN';
type TCollationLatin1 = 'LATIN1_GERMAN1_CI' | 'LATIN1_SWEDISH_CI' | 'LATIN1_DANISH_CI' | 'LATIN1_GERMAN2_CI' | 'LATIN1_BIN' | 'LATIN1_GENERAL_CI' | 'LATIN1_GENERAL_CS' | 'LATIN1_SPANISH_CI' | 'LATIN1_SWEDISH_NOPAD_CI' | 'LATIN1_NOPAD_BIN';
type TCollationLatin2 = 'LATIN2_CZECH_CS' | 'LATIN2_GENERAL_CI' | 'LATIN2_HUNGARIAN_CI' | 'LATIN2_CROATIAN_CI' | 'LATIN2_BIN' | 'LATIN2_GENERAL_NOPAD_CI' | 'LATIN2_NOPAD_BIN';
type TCollationSwe7 = 'SWE7_SWEDISH_CI' | 'SWE7_BIN' | 'SWE7_SWEDISH_NOPAD_CI' | 'SWE7_NOPAD_BIN';
type TCollationAscii = 'ASCII_GENERAL_CI' | 'ASCII_BIN' | 'ASCII_GENERAL_NOPAD_CI' | 'ASCII_NOPAD_BIN';
type TCollationUjis = 'UJIS_JAPANESE_CI' | 'UJIS_BIN' | 'UJIS_JAPANESE_NOPAD_CI' | 'UJIS_NOPAD_BIN';
type TCollationSjis = 'SJIS_JAPANESE_CI' | 'SJIS_BIN' | 'SJIS_JAPANESE_NOPAD_CI' | 'SJIS_NOPAD_BIN';
type TCollationHebrew = 'HEBREW_GENERAL_CI' | 'HEBREW_BIN' | 'HEBREW_GENERAL_NOPAD_CI' | 'HEBREW_NOPAD_BIN';
type TCollationTis620 = 'TIS620_THAI_CI' | 'TIS620_BIN' | 'TIS620_THAI_NOPAD_CI' | 'TIS620_NOPAD_BIN';
type TCollationEuckr = 'EUCKR_KOREAN_CI' | 'EUCKR_BIN' | 'EUCKR_KOREAN_NOPAD_CI' | 'EUCKR_NOPAD_BIN';
type TCollationKoi8u = 'KOI8U_GENERAL_CI' | 'KOI8U_BIN' | 'KOI8U_GENERAL_NOPAD_CI' | 'KOI8U_NOPAD_BIN';
type TCollationGb2312 = 'GB2312_CHINESE_CI' | 'GB2312_BIN' | 'GB2312_CHINESE_NOPAD_CI' | 'GB2312_NOPAD_BIN';
type TCollationGreek = 'GREEK_GENERAL_CI' | 'GREEK_BIN' | 'GREEK_GENERAL_NOPAD_CI' | 'GREEK_NOPAD_BIN';
type TCollationCp1250 = 'CP1250_GENERAL_CI' | 'CP1250_CZECH_CS' | 'CP1250_CROATIAN_CI' | 'CP1250_BIN' | 'CP1250_POLISH_CI' | 'CP1250_GENERAL_NOPAD_CI' | 'CP1250_NOPAD_BIN';
type TCollationGbk = 'GBK_CHINESE_CI' | 'GBK_BIN' | 'GBK_CHINESE_NOPAD_CI' | 'GBK_NOPAD_BIN';
type TCollationLatin5 = 'LATIN5_TURKISH_CI' | 'LATIN5_BIN' | 'LATIN5_TURKISH_NOPAD_CI' | 'LATIN5_NOPAD_BIN';
type TCollationArmscii8 = 'ARMSCII8_GENERAL_CI' | 'ARMSCII8_BIN' | 'ARMSCII8_GENERAL_NOPAD_CI' | 'ARMSCII8_NOPAD_BIN';
type TCollationUcs2 = 'UCS2_GENERAL_CI' | 'UCS2_BIN' | 'UCS2_UNICODE_CI' | 'UCS2_ICELANDIC_CI' | 'UCS2_LATVIAN_CI' | 'UCS2_ROMANIAN_CI' | 'UCS2_SLOVENIAN_CI' | 'UCS2_POLISH_CI' | 'UCS2_ESTONIAN_CI' | 'UCS2_SPANISH_CI' | 'UCS2_SWEDISH_CI' | 'UCS2_TURKISH_CI' | 'UCS2_CZECH_CI' | 'UCS2_DANISH_CI' | 'UCS2_LITHUANIAN_CI' | 'UCS2_SLOVAK_CI' | 'UCS2_SPANISH2_CI' | 'UCS2_ROMAN_CI' | 'UCS2_PERSIAN_CI' | 'UCS2_ESPERANTO_CI' | 'UCS2_HUNGARIAN_CI' | 'UCS2_SINHALA_CI' | 'UCS2_GERMAN2_CI' | 'UCS2_CROATIAN_MYSQL561_CI' | 'UCS2_UNICODE_520_CI' | 'UCS2_VIETNAMESE_CI' | 'UCS2_GENERAL_MYSQL500_CI' | 'UCS2_CROATIAN_CI' | 'UCS2_MYANMAR_CI' | 'UCS2_THAI_520_W2' | 'UCS2_GENERAL_NOPAD_CI' | 'UCS2_NOPAD_BIN' | 'UCS2_UNICODE_NOPAD_CI' | 'UCS2_UNICODE_520_NOPAD_CI';
type TCollationCp866 = 'CP866_GENERAL_CI' | 'CP866_BIN' | 'CP866_GENERAL_NOPAD_CI' | 'CP866_NOPAD_BIN';
type TCollationKeybcs2 = 'KEYBCS2_GENERAL_CI' | 'KEYBCS2_BIN' | 'KEYBCS2_GENERAL_NOPAD_CI' | 'KEYBCS2_NOPAD_BIN';
type TCollationMacce = 'MACCE_GENERAL_CI' | 'MACCE_BIN' | 'MACCE_GENERAL_NOPAD_CI' | 'MACCE_NOPAD_BIN';
type TCollationMacroman = 'MACROMAN_GENERAL_CI' | 'MACROMAN_BIN' | 'MACROMAN_GENERAL_NOPAD_CI' | 'MACROMAN_NOPAD_BIN';
type TCollationCp852 = 'CP852_GENERAL_CI' | 'CP852_BIN' | 'CP852_GENERAL_NOPAD_CI' | 'CP852_NOPAD_BIN';
type TCollationLatin7 = 'LATIN7_ESTONIAN_CS' | 'LATIN7_GENERAL_CI' | 'LATIN7_GENERAL_CS' | 'LATIN7_BIN' | 'LATIN7_GENERAL_NOPAD_CI' | 'LATIN7_NOPAD_BIN';
type TCollationUtf8mb4 = 'UTF8MB4_GENERAL_CI' | 'UTF8MB4_BIN' | 'UTF8MB4_UNICODE_CI' | 'UTF8MB4_ICELANDIC_CI' | 'UTF8MB4_LATVIAN_CI' | 'UTF8MB4_ROMANIAN_CI' | 'UTF8MB4_SLOVENIAN_CI' | 'UTF8MB4_POLISH_CI' | 'UTF8MB4_ESTONIAN_CI' | 'UTF8MB4_SPANISH_CI' | 'UTF8MB4_SWEDISH_CI' | 'UTF8MB4_TURKISH_CI' | 'UTF8MB4_CZECH_CI' | 'UTF8MB4_DANISH_CI' | 'UTF8MB4_LITHUANIAN_CI' | 'UTF8MB4_SLOVAK_CI' | 'UTF8MB4_SPANISH2_CI' | 'UTF8MB4_ROMAN_CI' | 'UTF8MB4_PERSIAN_CI' | 'UTF8MB4_ESPERANTO_CI' | 'UTF8MB4_HUNGARIAN_CI' | 'UTF8MB4_SINHALA_CI' | 'UTF8MB4_GERMAN2_CI' | 'UTF8MB4_CROATIAN_MYSQL561_CI' | 'UTF8MB4_UNICODE_520_CI' | 'UTF8MB4_VIETNAMESE_CI' | 'UTF8MB4_CROATIAN_CI' | 'UTF8MB4_MYANMAR_CI' | 'UTF8MB4_THAI_520_W2' | 'UTF8MB4_GENERAL_NOPAD_CI' | 'UTF8MB4_NOPAD_BIN' | 'UTF8MB4_UNICODE_NOPAD_CI' | 'UTF8MB4_UNICODE_520_NOPAD_CI';
type TCollationCp1251 = 'CP1251_BULGARIAN_CI' | 'CP1251_UKRAINIAN_CI' | 'CP1251_BIN' | 'CP1251_GENERAL_CI' | 'CP1251_GENERAL_CS' | 'CP1251_NOPAD_BIN' | 'CP1251_GENERAL_NOPAD_CI';
type TCollationUtf16 = 'UTF16_GENERAL_CI' | 'UTF16_BIN' | 'UTF16_UNICODE_CI' | 'UTF16_ICELANDIC_CI' | 'UTF16_LATVIAN_CI' | 'UTF16_ROMANIAN_CI' | 'UTF16_SLOVENIAN_CI' | 'UTF16_POLISH_CI' | 'UTF16_ESTONIAN_CI' | 'UTF16_SPANISH_CI' | 'UTF16_SWEDISH_CI' | 'UTF16_TURKISH_CI' | 'UTF16_CZECH_CI' | 'UTF16_DANISH_CI' | 'UTF16_LITHUANIAN_CI' | 'UTF16_SLOVAK_CI' | 'UTF16_SPANISH2_CI' | 'UTF16_ROMAN_CI' | 'UTF16_PERSIAN_CI' | 'UTF16_ESPERANTO_CI' | 'UTF16_HUNGARIAN_CI' | 'UTF16_SINHALA_CI' | 'UTF16_GERMAN2_CI' | 'UTF16_CROATIAN_MYSQL561_CI' | 'UTF16_UNICODE_520_CI' | 'UTF16_VIETNAMESE_CI' | 'UTF16_CROATIAN_CI' | 'UTF16_MYANMAR_CI' | 'UTF16_THAI_520_W2' | 'UTF16_GENERAL_NOPAD_CI' | 'UTF16_NOPAD_BIN' | 'UTF16_UNICODE_NOPAD_CI' | 'UTF16_UNICODE_520_NOPAD_CI' | 'UTF16LE_GENERAL_CI' | 'UTF16LE_BIN' | 'UTF16LE_GENERAL_NOPAD_CI' | 'UTF16LE_NOPAD_BIN';
type TCollationCp1256 = 'CP1256_GENERAL_CI' | 'CP1256_BIN' | 'CP1256_GENERAL_NOPAD_CI' | 'CP1256_NOPAD_BIN';
type TCollationCp1257 = 'CP1257_LITHUANIAN_CI' | 'CP1257_BIN' | 'CP1257_GENERAL_CI' | 'CP1257_NOPAD_BIN' | 'CP1257_GENERAL_NOPAD_CI';
type TCollationUtf32 = 'UTF32_GENERAL_CI' | 'UTF32_BIN' | 'UTF32_UNICODE_CI' | 'UTF32_ICELANDIC_CI' | 'UTF32_LATVIAN_CI' | 'UTF32_ROMANIAN_CI' | 'UTF32_SLOVENIAN_CI' | 'UTF32_POLISH_CI' | 'UTF32_ESTONIAN_CI' | 'UTF32_SPANISH_CI' | 'UTF32_SWEDISH_CI' | 'UTF32_TURKISH_CI' | 'UTF32_CZECH_CI' | 'UTF32_DANISH_CI' | 'UTF32_LITHUANIAN_CI' | 'UTF32_SLOVAK_CI' | 'UTF32_SPANISH2_CI' | 'UTF32_ROMAN_CI' | 'UTF32_PERSIAN_CI' | 'UTF32_ESPERANTO_CI' | 'UTF32_HUNGARIAN_CI' | 'UTF32_SINHALA_CI' | 'UTF32_GERMAN2_CI' | 'UTF32_CROATIAN_MYSQL561_CI' | 'UTF32_UNICODE_520_CI' | 'UTF32_VIETNAMESE_CI' | 'UTF32_CROATIAN_CI' | 'UTF32_MYANMAR_CI' | 'UTF32_THAI_520_W2' | 'UTF32_GENERAL_NOPAD_CI' | 'UTF32_NOPAD_BIN' | 'UTF32_UNICODE_NOPAD_CI' | 'UTF32_UNICODE_520_NOPAD_CI';
type TCollationBinary = 'BINARY';
type TCollationGeostd8 = 'GEOSTD8_GENERAL_CI' | 'GEOSTD8_BIN' | 'GEOSTD8_GENERAL_NOPAD_CI' | 'GEOSTD8_NOPAD_BIN';
type TCollationCp932 = 'CP932_JAPANESE_CI' | 'CP932_BIN' | 'CP932_JAPANESE_NOPAD_CI' | 'CP932_NOPAD_BIN';
type TCollationEucjpms = 'EUCJPMS_JAPANESE_CI' | 'EUCJPMS_BIN' | 'EUCJPMS_JAPANESE_NOPAD_CI' | 'EUCJPMS_NOPAD_BIN';

//#endregion

export {
    TType,
    TSentence,
    TDatabase,
    TReferenceOptions,
    TCharset,
    ICollation,
    TCollation,
    TEngine,
    TCompuestSentence
};